### ISSUE TITLE
[Eduardo Goicoechea] Project 4_ETL

### ISSUE THREAD

**Issue by Hrodward88** [Ironhack-Data-Madrid-Abril-2023/w4-project_ETL#15]
https://github.com/Hrodward88/DnDProject

**Comment by CharlyKill7** [comment]
Buen proyecto, Edu! Permíteme algunos comentarios:

- En cuanto al repo, bien la estructura de carpetas, aunque intenta meter también los .png en una carpeta de 'imagenes' y quitar los .csv que no uses. El readme está bien en el sentido en que explica bien lo que haces, pero te recomiendo dos cosas: reducir la extensión, por un lado, y dejar claro al principio de qué va le proyecto, por otro. 
Para lo primero, te aconsejo meter en desplegables la mayoría de imágenes que tienes, o la información más detallada, y dejar únicamente la idea general en la superficie. De esta forma el que quiere puede ampliar pero la primera impresión no es tan extensa. En cuanto a lo segundo, me refería al hecho de que las siglas ETL no están por ningún sitio, y ese es precisamente la definición más adecuada para lo que había que hacer. No estoy en contra del humor, ni mucho menos, pero podrías haber puesto "Proyecto de ETL (Web Scraping y cosas varias". De hecho, cuando dices "What happens when you let a man loose [...]" , mantienes ese humor pero en algo que no es tan central. Por ello, te animo a seguir con esa línea tan tuya pero intentando que lo realmente importante no sea sustituido. Eso sí, trata de mantener el mismo idioma en todo el readme.
- Respecto a la extracción, has trabajado bien las APIs y se nota que lo entiendes y, a propósito de la tranformación, todo correcto salvo por un detalle. En FinalGames tienes 3 nulos cuando lo pasas a .csv. Igual no había manera de encontrar el score para esas filas; si ese fuera le caso, intenta rellenarlo de alguna forma que te parezca adecuada para el problema que tienes entre manos.

En general, buen proyecto, Edu. El objetivo era obtener información de varias fuentes y, sobre todo, entender la implicación de decidirse por una u otra tabla, sabiendo qué transformaciones acarrearía tener unos datos u otros. Creo que en tu caso está cumplido. 

¡Sigue así, Edu!

**Comment by CharlyKill7** [comment]
Olvidé darte feedback de la presentación:

-	Muy bien exponer de pie.
-	Buen tono de voz, alto y claro. Aunque me gusta el tono de humor para clase, intenta cuidar el lenguaje, que aunque estamos en un entorno informal, tiene que servir de práctica para exposiciones mas serias como la del proyecto final, o las que vendrán en la vida laboral.
-	Intenta mirar más hacia los dos lados del público.
